logging:
    file:
        name: log/Ch11.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        org:
            hibernate: info
            springframework:
                security: debug
        root: info
server:
    servlet:
        context-path: /
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://13.124.190.156:3306/Jboard
        username: chhak
    devtools:
        livereload:
            enabled: true
        remote:
            restart:
                enabled: true
    jpa:
        database: mysql
        hibernate:
            # 배포할 때는 반드시 none, 개발할 때는 가급적 update
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true
    security:
        user:
            name: user
            password: 1234
    thymeleaf:
        cache: false
        # prefix 설정을 안하면 HTML 수정 후 브라우저에서 새로고침 반영안됨
        # 그리고 반드시 classpaht 경로로 쓰고 templates 마지막에 슬러쉬(/) 붙이면 배포파일 실행안됨
        # 그런데 마지막에 슬러쉬 붙이고 안붙이고는 본인의 Controller에서 리턴되는 view 경로의 슬러쉬 여부에 따라 달라짐
        prefix: classpath:/templates

    servlet:
        multipart:
            location: src/main/resources/static/file/
            max-file-size: 10MB


